global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: "edge_fleet_containers"
    metrics_path: "/metrics"
    static_configs:
      - targets:
          - "edge-gateway-01:8000"
          - "edge-gateway-02:8000"
